version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.node
    container_name: beauty_app_backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "3100:3100" 

  db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - app-network    

networks:
  app-network: 
    driver: bridge

volumes:
  postgres_data:
